package org.openiam.connector.sapume.service.wrapper;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.openiam.connector.sapume.service.SAPUMEConnectorService;
import org.openiam.connector.sapume.service.wrapper.SAPUMEConnectorService_Service;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-06-12T13:46:01.870+02:00
 * Generated source version: 2.7.15
 * 
 */
@WebServiceClient(name = "SAPUMEConnectorService", 
                  wsdlLocation = "file:/D:/EclipseKeplerMaven/workspace/SAPUMEConnector/wsdl/SAPUMEConnectorService.wsdl",
                  targetNamespace = "http://www.openiam.org/service/connector") 
public class SAPUMEConnectorService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.openiam.org/service/connector", "SAPUMEConnectorService");
    public final static QName SAPUMEConnectorServicePort = new QName("http://www.openiam.org/service/connector", "SAPUMEConnectorServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/EclipseKeplerMaven/workspace/SAPUMEConnector/wsdl/SAPUMEConnectorService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SAPUMEConnectorService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/EclipseKeplerMaven/workspace/SAPUMEConnector/wsdl/SAPUMEConnectorService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SAPUMEConnectorService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SAPUMEConnectorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAPUMEConnectorService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SAPUMEConnectorService
     */
    @WebEndpoint(name = "SAPUMEConnectorServicePort")
    public SAPUMEConnectorService getSAPUMEConnectorServicePort() {
        return super.getPort(SAPUMEConnectorServicePort, SAPUMEConnectorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPUMEConnectorService
     */
    @WebEndpoint(name = "SAPUMEConnectorServicePort")
    public SAPUMEConnectorService getSAPUMEConnectorServicePort(WebServiceFeature... features) {
        return super.getPort(SAPUMEConnectorServicePort, SAPUMEConnectorService.class, features);
    }

}
